name: Build Realme SM6375 Kernel with KernelSU Next

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          path: kernel/source
          ref: lineage-23.2

      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: ./kernel/source/
          config: vendor/holi-qgki_defconfig
          arch: arm64

          android-version: 12

          aosp-clang: true
          aosp-gcc: true

          ksu: true
          ksu-other: true
          ksu-url: https://github.com/KernelSU-Next/KernelSU-Next
          ksu-version: v0.9.5

          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
