name: Build Realme SM6375 Kernel with KernelSU Next

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/LineageOS/android_kernel_realme_sm6375.git
          kernel-branch: lineage-23.2
          config: vendor/holi-qgki_defconfig
          arch: arm64
          aosp-clang: true
          aosp-clang-version: r530567
          ksu-other: true
          ksu-url: https://github.com/KernelSU-Next/KernelSU-Next
          ksu-version: next
          anykernel3: true
